#!/usr/bin/env python3

def has_coffee_files(folder_path):
    """Check if any .coffee files exist in the given folder (recursively)."""
    import glob
    import os
    
    # Use glob to recursively search for .coffee files
    coffee_pattern = os.path.join(folder_path, '**', '*.coffee')
    coffee_files = glob.glob(coffee_pattern, recursive=True)
    
    # Filter out Mac metadata files
    coffee_files = [f for f in coffee_files if '__MACOSX' not in f]
    
    return len(coffee_files) > 0

def is_complex_coffee(folder_path):
    """Check if CoffeeScript files contain complex patterns (conditionals, loops, complex interpolation)."""
    import glob
    import os
    import re
    
    # Find all .coffee files, excluding __MACOSX directories
    coffee_pattern = os.path.join(folder_path, '**', '*.coffee')
    coffee_files = glob.glob(coffee_pattern, recursive=True)
    
    # Filter out Mac metadata files
    coffee_files = [f for f in coffee_files if '__MACOSX' not in f]
    
    if not coffee_files:
        return False
    
    # Patterns that indicate complexity
    complex_patterns = [
        r'if\s+.*\s+then',  # if-then statements
        r'for\s+.*\s+in',   # for loops
        r'while\s+',        # while loops
        r'when\s+',         # when statements
        r'#\{.*\?.*:.*\}',  # ternary operators in interpolation
        r'#\{.*forEach',    # forEach in interpolation
        r'#\{.*map\s*\(',   # map functions in interpolation
        r'#\{.*filter\s*\(', # filter functions in interpolation
        r'#\{.*if\s+',      # if statements in interpolation
        r'#\{.*for\s+',     # for loops in interpolation
    ]
    
    for coffee_file in coffee_files:
        try:
            with open(coffee_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                
            # Check for complex patterns
            for pattern in complex_patterns:
                if re.search(pattern, content, re.MULTILINE | re.DOTALL):
                    return True
                    
        except Exception:
            # If we can't read the file, assume it's not complex
            continue
    
    return False

def has_jsx_files(folder_path):
    """Check if any JSX files exist in the given folder (recursively)."""
    import glob
    import os
    
    # Use glob to recursively search for .jsx files
    jsx_pattern = os.path.join(folder_path, '**', '*.jsx')
    jsx_files = glob.glob(jsx_pattern, recursive=True)
    
    # Filter out Mac metadata files
    jsx_files = [f for f in jsx_files if '__MACOSX' not in f]
    
    return len(jsx_files) > 0

def main():
    """Generate a comprehensive CSV report from widget data, categories, and coffee detection results."""
    import json
    import csv
    import os
    import glob
    from urllib.parse import urlparse
    
    # Read the widget list JSON file
    with open('widget_list.json', 'r') as f:
        data = json.load(f)
    
    # Categories will be generated by AI during curation
    
    # Read download status file
    download_status = {}
    try:
        with open('download_status.json', 'r') as f:
            download_status = json.load(f)
        print(f"Loaded download status for {len(download_status)} widgets")
    except FileNotFoundError:
        print("Warning: download_status.json not found")
        print("Coffee detection will be set to 'Unknown' for all widgets")
    except Exception as e:
        print(f"Warning: Error reading download status: {e}")
        print("Coffee detection will be set to 'Unknown' for all widgets")
    
    # Check for downloads directory
    downloads_dir = 'downloads'
    if not os.path.exists(downloads_dir):
        print(f"Warning: Downloads directory not found at {downloads_dir}")
        print("Coffee detection will be set to 'Unknown'")
    
    # Prepare CSV output file
    csv_filename = 'widget_processing_results.csv'
    csv_headers = ['OS_widget_id', 'OS_name', 'OS_author', 'OS_description', 'PS_filename', 'OS_download_url', 'AI_category', 'AI_secondary_category', 'AI_prompt', 'PS_iscoffee', 'PS_complexcoffee', 'PS_isJSX', 'PS_widgetfoldername', 'CT_set', 'CT_comment']
    
    # Process all widgets in the array
    widgets = data['widgets']
    csv_data = []
    
    for widget in widgets:
        widget_id = widget['id']
        name = widget.get('name', 'Unknown')
        author = widget.get('author', 'Unknown')
        description = widget.get('description', 'No description available')
        download_url = widget['downloadUrl']
        
        # Extract filename from URL
        parsed_url = urlparse(download_url)
        filename = parsed_url.path.split('/')[-1]
        if not filename.endswith('.zip'):
            filename = f"{widget_id}.zip"
        
        # Determine widget folder name (remove .zip extension)
        widget_folder_name = filename[:-4] if filename.endswith('.zip') else filename
        
        # Initialize AI_* fields as empty (to be filled by AI later)
        category = ''
        secondary_category = ''
        ai_prompt = ''
        
        # Check for coffee files based on download status
        iscoffee = 'Unknown'
        complexcoffee = False
        isjsx = 'Unknown'
        if widget_id in download_status:
            if download_status[widget_id] == 'success':
                # Only check for files if download was successful
                if os.path.exists(downloads_dir):
                    # Create folder name (remove .zip extension)
                    folder_name = filename[:-4] if filename.endswith('.zip') else filename
                    extract_path = os.path.join(downloads_dir, folder_name)
                    
                    if os.path.exists(extract_path):
                        # Check for CoffeeScript files
                        if has_coffee_files(extract_path):
                            iscoffee = 'Y'
                            complexcoffee = is_complex_coffee(extract_path)
                            print(f"Found .coffee files in: {folder_name} (Complex: {complexcoffee})")
                        else:
                            iscoffee = 'N'
                        
                        # Check for JSX files (independent of CoffeeScript)
                        if has_jsx_files(extract_path):
                            isjsx = 'Y'
                            print(f"Found .jsx files in: {folder_name}")
                        else:
                            isjsx = 'N'
                    else:
                        iscoffee = 'Extraction Failed'
                        isjsx = 'Extraction Failed'
                else:
                    iscoffee = 'Downloads Directory Missing'
                    isjsx = 'Downloads Directory Missing'
            elif download_status[widget_id] == 'failed':
                iscoffee = 'Download Failed'
                isjsx = 'Download Failed'
            else:
                iscoffee = 'Unknown Status'
                isjsx = 'Unknown Status'
        else:
            iscoffee = 'Not Attempted'
            isjsx = 'Not Attempted'
        
        # Add row to CSV data
        csv_data.append([widget_id, name, author, description, filename, download_url, category, secondary_category, ai_prompt, iscoffee, complexcoffee, isjsx, widget_folder_name, '', ''])
    
    # Write CSV file
    with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(csv_headers)
        writer.writerows(csv_data)
    
    print(f"Generated report for {len(widgets)} widgets")
    print(f"Results saved to: {csv_filename}")

if __name__ == "__main__":
    main()
